export const REPORT_ID = 'reportId'
export const ADD_REPORT = 'add-report'

export const NAVIGATION_IDS  = {
    [REPORT_ID]:REPORT_ID,
    [ADD_REPORT]: ADD_REPORT
}

export const TRANSCAT_ORIGIN_AMAZON = 'AMAZON_ORIGIN';
export const TRANSCAT_ORIGIN_OTHER  = 'OTHER_ORIGIN';

export const TRANSCAT_ORIGINS = {
    [TRANSCAT_ORIGIN_AMAZON]:TRANSCAT_ORIGIN_AMAZON,
    [TRANSCAT_ORIGIN_OTHER]: TRANSCAT_ORIGIN_OTHER
}